### ISSUE TITLE
failed to create new OS thread

### ISSUE THREAD

**Issue by siddharthvp** [addshore/mediawiki-docker-dev#135]
Getting this error in `docker-compose up`:

```
web_1              | -> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
web_1              | -> Executing /opt/docker/provision/entrypoint.d/10-php-debugger.sh
web_1              | PHP-Debugger: Xdebug enabled
web_1              |  - Removing PHP module blackfire
web_1              | -> Executing /opt/docker/provision/entrypoint.d/20-apache-dev.sh
web_1              | runtime: failed to create new OS thread (have 2 already; errno=22)
web_1              | fatal error: newosproc
web_1              |
web_1              | runtime stack:
web_1              | runtime.throw(0x6430dc, 0x9)
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95
web_1              | runtime.newosproc(0xc42002c000, 0xc42003c000)
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/os_linux.go:163 +0x18c
web_1              | runtime.newm(0x650dd0, 0x0)
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1628 +0x137
web_1              | runtime.main.func1()
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:126 +0x36
web_1              | runtime.systemstack(0x75bb00)
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:327 +0x79
web_1              | runtime.mstart()
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:1132
web_1              |
web_1              | goroutine 1 [running]:
web_1              | runtime.systemstack_switch()
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:281 fp=0xc420028788 sp=0xc420028780
web_1              | runtime.main()
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/proc.go:127 +0x6c fp=0xc4200287e0 sp=0xc420028788
web_1              | runtime.goexit()
web_1              | 	/usr/local/Cellar/go/1.8.1/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200287e8 sp=0xc4200287e0
```

I'm using Docker for Mac.

**Comment by addshore** [comment]
Hi there, 

I no longer support this environment, and I just updated the README to reflect this.
https://github.com/addshore/mediawiki-docker-dev/commit/ed6bac58325de27b53d3791b5e2443571d6e699a

You should go and give mwcli a go!

It has the same functionality as this environment, and more!
https://www.mediawiki.org/wiki/Cli
